apiVersion: v1
kind: Service
metadata:
  name: cohort-builder
spec:
  ports:
    - port: 80
  selector:
    app: cohort-builder
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cohort-builder
spec:
  selector:
    matchLabels:
      app: cohort-builder
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cohort-builder
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: sui-sites-enabled-configmap
      containers:
        - image: tcia/prism-sui:latest
          name: sui-react
          ports:
            - containerPort: 80
              name: sui-react
          envFrom:
            - configMapRef:
                name: url-configmap
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
        - image: tcia/prism-sapi:latest
          name: sui-sapi
          envFrom:
            - configMapRef:
                name: url-configmap
          ports:
            - containerPort: 3000
              name: sui-sapi
