apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  ports:
  - port: 80
  selector:
    app: demo
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: tcia/aries-demo:latest
        name: demo
        ports:
        - containerPort: 80
          name: demo
